config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  scope module: :user do
    root "homes#top"
    get 'about' => 'homes#about'
    get "/search", to: "searches#search"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users, only: [:index, :show, :edit, :update, :destroy]do
        member do
          get :favorites
        end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  
  namespace :admin do
    root 'homes#top'
    get "/search", to: "searches#search"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts do
      resources :post_comments
    end
  end
  
devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @content = params[:content]
    @records = User.search_for(@content).page(params[:page]).per(10)
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  def search
    @content = params[:content]
    @records = User.search_for(@content)
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/views/admin/searches/_form.html.erb
<h3>煙検索</h3>
    <div class="serch-form">
      <%= form_with(scope: :search, url: admin_posts_path, method: :get, local:true) do |f| %>
          <div class="form-group" id="star">
            <%= f.label "評価" %>
            <%= f.hidden_field :star, id: :review_star, value: search_params&.fetch(:star, nil), class: 'form-control' %>
            <div id="post_raty"></div>
          </div>
          <script>
            $(document).on('turbolinks:load', function() {
              let elem = document.querySelector('#post_raty');
              if (elem == null) return;
              elem.innerHTML = ""
              let opt = {
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                scoreName: 'search[star]',
              };
              raty(elem, opt);
            });
          </script>

        <div class="form-group">
          <%= f.label "タイトル" %>
          <%= f.text_field :title, value: search_params&.fetch(:title, nil), class: 'form-control',placeholder: "店名や作品名など" %>
        </div>
        <div class="form-group">
          <%= f.label "場所" %>
          <%= f.text_field :location, value: search_params&.fetch(:location, nil), class: 'form-control',placeholder: "店舗住所等" %>
        </div>
        <div class="form-group">
          <%= f.label "金額" %>
          <%= f.number_field :price_from, value: search_params&.fetch(:price_from, nil),class: 'form-control', placeholder: "円" %> ~ <%= f.number_field :price_to, value: search_params&.fetch(:price_to, nil),class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "製作者" %>
          <%= f.select :player, Post.players_i18n.invert, selected: search_params&.fetch(:player, nil), class: 'form-control', include_blank: '選択' %>
        </div>
        <div class="form-group">
          <%= f.label "味のジャンル" %>
          <%= f.select :flavor_genre, Post.flavor_genres_i18n.invert, selected: search_params&.fetch(:flavor_genre, nil), class: 'form-control', include_blank: '選択' %>
        </div>
        <div class="form-group">
          <%= f.label "ニコチン" %>
          <div class="form-check form-check-inline">
            <%= f.radio_button :nicotine, true, id: 'nicotine_true', class: 'form-check-input', checked: search_params&.fetch(:nicotine, nil) == 'true' %>
            <%= f.label 'nicotine_true', 'あり', class: 'form-check-label' %>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :nicotine, false, id: 'nicotine_false', class: 'form-check-input', checked: search_params&.fetch(:nicotine, nil) == 'false' %>
            <%= f.label 'nicotine_false', 'なし', class: 'form-check-label' %>
          </div>
        </div>
        <div>
          <p>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#tagContent">
              詳細検索
            </button>
          </p>
          <div id="tagContent" class="collapse">
            <div class="form-group">
              <%= f.label "ボトルオプション" %>
              <div class="form-check form-check-inline">
                <%= f.radio_button :bottle_option, true, id: 'bottle_option_true', class: 'form-check-input', checked: search_params&.fetch(:bottle_option, nil) == 'true' %>
                <%= f.label 'bottle_option_true', 'あり', class: 'form-check-label' %>
              </div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :bottle_option, false, id: 'bottle_option_false', class: 'form-check-input', checked: search_params&.fetch(:bottle_option, nil) == 'false' %>
                <%= f.label 'bottle_option_false', 'なし', class: 'form-check-label' %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label "吸いごたえ" %>
              <%= f.select :smoking_level, Post.smoking_levels_i18n.invert, selected: search_params&.fetch(:smoking_level, nil), class: 'form-control', include_blank: '選択' %>
            </div>
            <div class="form-group">
              <%= f.label "煙の味の濃さ" %>
              <%= f.select :smoking_taste_level, Post.smoking_taste_levels_i18n.invert, selected: search_params&.fetch(:smoking_taste_level, nil), class: 'form-control', include_blank: '選択' %>
            </div>
            <div class="form-group">
              <%= f.label "HMSジャンル" %>
              <%= f.select :hms_genre, Post.hms_genres_i18n.invert, selected: search_params&.fetch(:hms_genre, nil), class: 'form-control', include_blank: '選択' %>
            </div>
            <div class="form-group">
              <%= f.label "トップジャンル" %>
              <%= f.select :top_genre, Post.top_genres_i18n.invert, selected: search_params&.fetch(:top_genre, nil), class: 'form-control', include_blank: '選択' %>
            </div>
            <div class="form-group">
              <%= f.label "喫煙時間" %>
              <%= f.number_field :duration_from, value: search_params&.fetch(:duration_from, nil),class: 'form-control', placeholder: "分" %> ~ <%= f.number_field :duration_to, value: search_params&.fetch(:duration_to, nil),class: 'form-control'  %>
            </div>
            <div class="form-group">
              <%= f.label "フレーバー容量" %>
              <%= f.number_field :flavor_capacity_from, value: search_params&.fetch(:flavor_capacity_from, nil),class: 'form-control', placeholder: "グラム" %> ~ <%= f.number_field :flavor_capacity_to, value: search_params&.fetch(:flavor_capacity_to, nil),class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label "フレーバーメーカー" %>
              <%= f.text_field :flavor_maker, value: search_params&.fetch(:flavor_maker, nil), class: 'form-control',placeholder: "アルファーヘル、ドザジ" %>
            </div>
          </div>
        </div>
        <div class="actions">
          <%= f.submit "検索する", class: 'btn btn-success form-control' %>
        </div>
      <% end %>
    </div>

app/views/admin/searches/search.html.erb
<div class='container'>
  <h3>ユーザネーム"<%= @content %>"の検索結果</h3>
  <% if @records.exists? %>
  <table class='table table-hover table-sm'>
    <thead>
      <tr>
        <th>ユーザid</th>
        <th></th>
        <th>ユーザネーム</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= image_tag user.get_profile_image(50,50) %>
          </td>
          <td><%= link_to user.name, admin_user_path(user) %></td>
          <% if user.is_active == true %>
            <td class="text-success">有効</td>
          <% else %>
            <td class="text-danger">退会</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class ="d-flex justify-content-center">
    <%= paginate @records %>
  </div>
  <% else %>
    <h4 class ="mt-5 text-center">ユーザがみつかりません</h4>
  <% end %>
</div>