config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  scope module: :user do
    root "homes#top"
    get 'about' => 'homes#about'
    get "/search", to: "searches#search"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users, only: [:index, :show, :edit, :update, :destroy]do
        member do
          get :favorites
        end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  
  namespace :admin do
    root 'homes#top'
    get "/search", to: "searches#search"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts do
      resources :post_comments
    end
  end
  
devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin! 
  def top
    @users = User.all.page(params[:page]).per(10)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class='container my-3'>
  <div class='row'>
    <div class='col-md-3'>
      <h3>ユーザ検索</h3>
      <%= form_with url: admin_search_path, method: :get, local:true do |f| %>
        <%= f.text_field :content %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
    <div class='col-md-9 shadow'>
      <h2>ユーザ一覧</h2>
      <table class='table table-hover table-sm'>
        <thead>
          <tr>
            <th>ユーザid</th>
            <th></th>
            <th>ユーザネーム</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= image_tag user.get_profile_image(50,50), class: "profile-image" %>
              </td>
              <td><%= link_to user.name, admin_user_path(user) %></td>
              <% if user.is_active == true %>
                <td class="text-success">有効</td>
              <% else %>
                <td class="text-danger">退会</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class ="d-flex justify-content-center">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>