config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  scope module: :user do
    root "homes#top"
    get 'about' => 'homes#about'
    get "/search", to: "searches#search"
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users, only: [:index, :show, :edit, :update, :destroy]do
        member do
          get :favorites
        end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
  
  namespace :admin do
    root 'homes#top'
    get "/search", to: "searches#search"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts do
      resources :post_comments
    end
  end
  
devise_for :user,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
   validates :comment, presence:true ,length: { maximum: 100 }
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to request.referer, notice: 'コメントを削除しました。'
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController
  before_action :is_post_matching_login_user, only: [:destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.post_id = @post.id
    @comment.save
  end

  def destroy
    @comment = PostComment.find(params[:id])
    PostComment.find(params[:id]).destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/views/admin/post_comments/_counter.html.erb
<i class="fa-solid fa-comment"></i><%= post.post_comments.count %>

app/views/admin/post_comments/_index.html.erb
<h4>コメント一覧</h4>
<% if post.post_comments.exists? %>
<table>
  <tbody>
    <% post.post_comments.each do |post_comment| %>
    <tr>
      <td>
        <%= link_to admin_user_path(post_comment.user) do %>
          <%= image_tag post_comment.user.get_profile_image(50,50) %><br>
          <%= post_comment.user.name %>
        <% end %>
      </td>
      <td><%= post_comment.comment %></td>
      <td>
        <%= link_to "削除", admin_post_post_comment_path(post, post_comment), method: :delete, class: "btn btn-sm btn-danger float-end", remote: true, data: { confirm: '本当に削除しますか?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h6 class ="m-5 text-center">コメントはありません</h6>
<% end %>